//------------------------------------------------------------------------------
// <auto-generated>
//     Version attributes backed by GitVersion.MsBuild constants.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyVersion(GitVersionInformation.AssemblySemVer)]
[assembly: AssemblyFileVersion(GitVersionInformation.AssemblySemFileVer)]
[assembly: AssemblyInformationalVersion(GitVersionInformation.InformationalVersion)]
