//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roma.Host.Properties
{
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager? resourceMan;
        private static global::System.Globalization.CultureInfo? resourceCulture;

        internal Resources()
        {
        }

        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                resourceMan ??= new global::System.Resources.ResourceManager("Roma.Host.Properties.Resources", typeof(Resources).Assembly);
                return resourceMan;
            }
        }

        internal static global::System.Globalization.CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string Analyze => ResourceManager.GetString("Analyze", resourceCulture) ?? "Analyze";

        internal static string ScopeSearchToThisAssembly => ResourceManager.GetString("ScopeSearchToThisAssembly", resourceCulture) ?? "Scope Search to This Assembly";
    }
}
